# Use Travis's container based infrastructure
sudo: required

rvm:
  - 2.0.0

install:
  - sudo echo 'deb http://download.virtualbox.org/virtualbox/debian precise contrib' > /etc/apt/sources.list
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox-5.0
  - sudo wget -nv https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb
  - sudo dpkg -i vagrant_1.8.1_x86_64.deb
  - bundle install
  - vagrant plugin install vagrant-winrm
