# Use Travis' Trusty beta
sudo: required
dist: trusty

rvm:
  - 2.0.0

install:
  - sudo add-apt-repository "deb http://download.virtualbox.org/virtualbox/debian trusty contrib"
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get install -y linux-headers-$(uname -r) virtualbox-5.0
  - sudo cat /var/log/vbox-install.log
  - sudo wget -nv https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb
  - sudo dpkg -i vagrant_1.8.1_x86_64.deb
  - bundle install
  - vagrant plugin install vagrant-winrm
  - sudo usermod -a -G vboxusers $USER

script:
  - which bundle
  - echo $PATH
  - echo $USER
  - sudo -E env "PATH=$PATH" echo $PATH
  - sudo -E env "PATH=$PATH" bundle exec rake
  - bundle exec rake
