# Use Travis' Trusty beta
sudo: required
dist: trusty

rvm:
  - 2.0.0

install:
  - sudo apt-get update -q
  - sudo apt-get install -y linux-headers-$(uname -r)
  - sudo wget -nv http://download.virtualbox.org/virtualbox/5.0.14/virtualbox-5.0_5.0.14-105127~Ubuntu~precise_amd64.deb
  - sudo apt-get install libsdl1.2debian libvpx1
  - sudo dpkg -i virtualbox-5.0_5.0.14-105127~Ubuntu~precise_amd64.deb
  - sudo cat /var/log/vbox-install.log
  - sudo wget -nv https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb
  - sudo dpkg -i vagrant_1.8.1_x86_64.deb
  - bundle install
  - vagrant plugin install vagrant-winrm
  - sudo usermod -a -G vboxusers $USER

script:
  - which bundle
  - echo $PATH
  - echo $USER
  - sudo -E -u $USER -c 'echo $PATH'
  - sudo -E -u $USER -c 'bundle exec rake'
